from PyQt5 import QtCore, QtGui, QtWidgets
class Task():
    def __init__(self, parent, name, index):
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 120, 391, (53 * index)))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.task = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.task.setContentsMargins(0, 0, 0, 0)
        self.task.setObjectName("task")
        self.task_name = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.task_name.setFont(font)
        self.task_name.setObjectName("task_name")
        self.task.addWidget(self.task_name)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.task.addItem(spacerItem)

        self.do = QtWidgets.QPushButton(self.horizontalLayoutWidget)

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)

        self.do.setFont(font)
        self.do.setStyleSheet("color: rgb(43, 255, 20);")
        self.do.setObjectName("do")
        self.task.addWidget(self.do)

        self.dont = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        self.dont.setFont(font)
        self.dont.setStyleSheet("color: rgb(170, 0, 0);")
        self.dont.setObjectName("dont")
        self.task.addWidget(self.dont)
        self.task_name.setText(name)
        self.do.setText("✓")
        self.dont.setText("❌")