# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calendar-day.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.day_item = QtWidgets.QPushButton(self.centralwidget)
        self.day_item.setGeometry(QtCore.QRect(30, 10, 101, 101))
        self.day_item.setText("")
        self.day_item.setObjectName("day_item")
        self.day_number = QtWidgets.QLabel(self.centralwidget)
        self.day_number.setGeometry(QtCore.QRect(70, 30, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.day_number.setFont(font)
        self.day_number.setObjectName("day_number")
        self.day_name = QtWidgets.QLabel(self.centralwidget)
        self.day_name.setGeometry(QtCore.QRect(30, 80, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.day_name.setFont(font)
        self.day_name.setObjectName("day_name")
        self.day_name_2 = QtWidgets.QLabel(self.centralwidget)
        self.day_name_2.setGeometry(QtCore.QRect(150, 80, 91, 16))
        font = QtGui.QFont()
        # 120
        font.setFamily("Arial")
        font.setPointSize(11)
        self.day_name_2.setFont(font)
        self.day_name_2.setObjectName("day_name_2")
        self.day_number_2 = QtWidgets.QLabel(self.centralwidget)
        self.day_number_2.setGeometry(QtCore.QRect(190, 30, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.day_number_2.setFont(font)
        self.day_number_2.setObjectName("day_number_2")
        self.day_item_2 = QtWidgets.QPushButton(self.centralwidget)
        self.day_item_2.setGeometry(QtCore.QRect(150, 10, 101, 101))
        self.day_item_2.setText("")
        self.day_item_2.setObjectName("day_item_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.day_number.setText(_translate("MainWindow", "1"))
        self.day_name.setText(_translate("MainWindow", "Понедельник"))
        self.day_name_2.setText(_translate("MainWindow", "Понедельник"))
        self.day_number_2.setText(_translate("MainWindow", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
